# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.26.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.26.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/mathurincartron/Documents/06 - Cours/04-Stage/StageXLIM"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/mathurincartron/Documents/06 - Cours/04-Stage/StageXLIM"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.26.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.26.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/mathurincartron/Documents/06 - Cours/04-Stage/StageXLIM/CMakeFiles" "/Users/mathurincartron/Documents/06 - Cours/04-Stage/StageXLIM//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/mathurincartron/Documents/06 - Cours/04-Stage/StageXLIM/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gpuSimulation

# Build rule for target.
gpuSimulation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpuSimulation
.PHONY : gpuSimulation

# fast build rule for target.
gpuSimulation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/build
.PHONY : gpuSimulation/fast

src/gpuObjectVersion/Map.o: src/gpuObjectVersion/Map.cpp.o
.PHONY : src/gpuObjectVersion/Map.o

# target to build an object file
src/gpuObjectVersion/Map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/src/gpuObjectVersion/Map.cpp.o
.PHONY : src/gpuObjectVersion/Map.cpp.o

src/gpuObjectVersion/Map.i: src/gpuObjectVersion/Map.cpp.i
.PHONY : src/gpuObjectVersion/Map.i

# target to preprocess a source file
src/gpuObjectVersion/Map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/src/gpuObjectVersion/Map.cpp.i
.PHONY : src/gpuObjectVersion/Map.cpp.i

src/gpuObjectVersion/Map.s: src/gpuObjectVersion/Map.cpp.s
.PHONY : src/gpuObjectVersion/Map.s

# target to generate assembly for a file
src/gpuObjectVersion/Map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/src/gpuObjectVersion/Map.cpp.s
.PHONY : src/gpuObjectVersion/Map.cpp.s

src/gpuObjectVersion/Population.o: src/gpuObjectVersion/Population.cpp.o
.PHONY : src/gpuObjectVersion/Population.o

# target to build an object file
src/gpuObjectVersion/Population.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/src/gpuObjectVersion/Population.cpp.o
.PHONY : src/gpuObjectVersion/Population.cpp.o

src/gpuObjectVersion/Population.i: src/gpuObjectVersion/Population.cpp.i
.PHONY : src/gpuObjectVersion/Population.i

# target to preprocess a source file
src/gpuObjectVersion/Population.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/src/gpuObjectVersion/Population.cpp.i
.PHONY : src/gpuObjectVersion/Population.cpp.i

src/gpuObjectVersion/Population.s: src/gpuObjectVersion/Population.cpp.s
.PHONY : src/gpuObjectVersion/Population.s

# target to generate assembly for a file
src/gpuObjectVersion/Population.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/src/gpuObjectVersion/Population.cpp.s
.PHONY : src/gpuObjectVersion/Population.cpp.s

src/gpuObjectVersion/Settings.o: src/gpuObjectVersion/Settings.cpp.o
.PHONY : src/gpuObjectVersion/Settings.o

# target to build an object file
src/gpuObjectVersion/Settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/src/gpuObjectVersion/Settings.cpp.o
.PHONY : src/gpuObjectVersion/Settings.cpp.o

src/gpuObjectVersion/Settings.i: src/gpuObjectVersion/Settings.cpp.i
.PHONY : src/gpuObjectVersion/Settings.i

# target to preprocess a source file
src/gpuObjectVersion/Settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/src/gpuObjectVersion/Settings.cpp.i
.PHONY : src/gpuObjectVersion/Settings.cpp.i

src/gpuObjectVersion/Settings.s: src/gpuObjectVersion/Settings.cpp.s
.PHONY : src/gpuObjectVersion/Settings.s

# target to generate assembly for a file
src/gpuObjectVersion/Settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/src/gpuObjectVersion/Settings.cpp.s
.PHONY : src/gpuObjectVersion/Settings.cpp.s

src/gpuObjectVersion/Simulation.o: src/gpuObjectVersion/Simulation.cpp.o
.PHONY : src/gpuObjectVersion/Simulation.o

# target to build an object file
src/gpuObjectVersion/Simulation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/src/gpuObjectVersion/Simulation.cpp.o
.PHONY : src/gpuObjectVersion/Simulation.cpp.o

src/gpuObjectVersion/Simulation.i: src/gpuObjectVersion/Simulation.cpp.i
.PHONY : src/gpuObjectVersion/Simulation.i

# target to preprocess a source file
src/gpuObjectVersion/Simulation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/src/gpuObjectVersion/Simulation.cpp.i
.PHONY : src/gpuObjectVersion/Simulation.cpp.i

src/gpuObjectVersion/Simulation.s: src/gpuObjectVersion/Simulation.cpp.s
.PHONY : src/gpuObjectVersion/Simulation.s

# target to generate assembly for a file
src/gpuObjectVersion/Simulation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/src/gpuObjectVersion/Simulation.cpp.s
.PHONY : src/gpuObjectVersion/Simulation.cpp.s

src/gpuObjectVersion/main.o: src/gpuObjectVersion/main.cpp.o
.PHONY : src/gpuObjectVersion/main.o

# target to build an object file
src/gpuObjectVersion/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/src/gpuObjectVersion/main.cpp.o
.PHONY : src/gpuObjectVersion/main.cpp.o

src/gpuObjectVersion/main.i: src/gpuObjectVersion/main.cpp.i
.PHONY : src/gpuObjectVersion/main.i

# target to preprocess a source file
src/gpuObjectVersion/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/src/gpuObjectVersion/main.cpp.i
.PHONY : src/gpuObjectVersion/main.cpp.i

src/gpuObjectVersion/main.s: src/gpuObjectVersion/main.cpp.s
.PHONY : src/gpuObjectVersion/main.s

# target to generate assembly for a file
src/gpuObjectVersion/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/src/gpuObjectVersion/main.cpp.s
.PHONY : src/gpuObjectVersion/main.cpp.s

src/gpuObjectVersion/utils/utils.o: src/gpuObjectVersion/utils/utils.cpp.o
.PHONY : src/gpuObjectVersion/utils/utils.o

# target to build an object file
src/gpuObjectVersion/utils/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/src/gpuObjectVersion/utils/utils.cpp.o
.PHONY : src/gpuObjectVersion/utils/utils.cpp.o

src/gpuObjectVersion/utils/utils.i: src/gpuObjectVersion/utils/utils.cpp.i
.PHONY : src/gpuObjectVersion/utils/utils.i

# target to preprocess a source file
src/gpuObjectVersion/utils/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/src/gpuObjectVersion/utils/utils.cpp.i
.PHONY : src/gpuObjectVersion/utils/utils.cpp.i

src/gpuObjectVersion/utils/utils.s: src/gpuObjectVersion/utils/utils.cpp.s
.PHONY : src/gpuObjectVersion/utils/utils.s

# target to generate assembly for a file
src/gpuObjectVersion/utils/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuSimulation.dir/build.make CMakeFiles/gpuSimulation.dir/src/gpuObjectVersion/utils/utils.cpp.s
.PHONY : src/gpuObjectVersion/utils/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gpuSimulation"
	@echo "... src/gpuObjectVersion/Map.o"
	@echo "... src/gpuObjectVersion/Map.i"
	@echo "... src/gpuObjectVersion/Map.s"
	@echo "... src/gpuObjectVersion/Population.o"
	@echo "... src/gpuObjectVersion/Population.i"
	@echo "... src/gpuObjectVersion/Population.s"
	@echo "... src/gpuObjectVersion/Settings.o"
	@echo "... src/gpuObjectVersion/Settings.i"
	@echo "... src/gpuObjectVersion/Settings.s"
	@echo "... src/gpuObjectVersion/Simulation.o"
	@echo "... src/gpuObjectVersion/Simulation.i"
	@echo "... src/gpuObjectVersion/Simulation.s"
	@echo "... src/gpuObjectVersion/main.o"
	@echo "... src/gpuObjectVersion/main.i"
	@echo "... src/gpuObjectVersion/main.s"
	@echo "... src/gpuObjectVersion/utils/utils.o"
	@echo "... src/gpuObjectVersion/utils/utils.i"
	@echo "... src/gpuObjectVersion/utils/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

